[package]
name = "localcloud-analytics"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
license-file.workspace = true
description = "Native AWS analytics services"

[dependencies]
localcloud-core.workspace = true
async-trait.workspace = true
apache-avro = { version = "=0.21.0", default-features = false }
axum.workspace = true
bytes.workspace = true
dashmap.workspace = true
http.workspace = true
quick-xml = "=0.42.0"
parquet = { version = "=59.3.0", default-features = false, features = ["snap", "zstd", "flate2-zlib-rs"] }
serde.workspace = true
serde_json.workspace = true
tokio.workspace = true
uuid.workspace = true

[dev-dependencies]
localcloud-s3.workspace = true
