[package]
name = "localcloud"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
description = "Native Linux AWS emulator"

[[bin]]
name = "localcloud"
path = "src/main.rs"

[dependencies]
localcloud-core.workspace = true
localcloud-state.workspace = true
localcloud-compute.workspace = true
localcloud-lambda.workspace = true
localcloud-iam-sts.workspace = true
localcloud-dynamodb.workspace = true
localcloud-s3.workspace = true
localcloud-sqs.workspace = true
localcloud-sns.workspace = true
localcloud-eventbridge.workspace = true
localcloud-stepfunctions.workspace = true
localcloud-apigateway.workspace = true
localcloud-cloudformation.workspace = true
localcloud-ecr.workspace = true
localcloud-ecs.workspace = true
localcloud-ec2.workspace = true
localcloud-elbv2.workspace = true
localcloud-kms.workspace = true
localcloud-ssm.workspace = true
localcloud-secretsmanager.workspace = true
localcloud-cloudwatch-monitoring.workspace = true
localcloud-cloudwatch-logs.workspace = true
localcloud-rds-data.workspace = true
localcloud-rds.workspace = true
localcloud-analytics.workspace = true
localcloud-kinesis.workspace = true
localcloud-firehose.workspace = true
localcloud-xray.workspace = true
localcloud-cloudtrail.workspace = true
localcloud-route53.workspace = true
localcloud-arc.workspace = true
localcloud-region-switch.workspace = true
localcloud-wafv2.workspace = true
localcloud-cognito.workspace = true
localcloud-acm.workspace = true
localcloud-cloudfront.workspace = true
tokio.workspace = true
async-trait.workspace = true
tracing.workspace = true
serde_json.workspace = true
flate2.workspace = true
