[package]
name = "localcloud-cloudwatch-monitoring"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
license-file.workspace = true
description = "Native CloudWatch Monitoring emulation for localcloud"

[dependencies]
localcloud-core.workspace = true
async-trait.workspace = true
axum.workspace = true
http.workspace = true
serde.workspace = true
serde_json.workspace = true
tokio.workspace = true
thiserror.workspace = true
time.workspace = true
