[package]
name = "localcloud-ecs"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
description = "Native Amazon ECS control-plane subset"

[dependencies]
localcloud-core.workspace = true
async-trait.workspace = true
axum.workspace = true
bytes.workspace = true
http.workspace = true
serde.workspace = true
serde_json.workspace = true
uuid.workspace = true
tokio.workspace = true
